version: '2.4'

x-common-pkg:
   &default-pkg
    volumes:
      - ../src/${COMPOSE_PROJECT_NAME}:${HOMEDIR}/${COMPOSE_PROJECT_NAME}:ro
      - ../src/setup.py:${HOMEDIR}/setup.py:ro
      - ../LICENSE:${HOMEDIR}/LICENSE:ro
      - ../README.md:${HOMEDIR}/README.md:ro

services:

  pkg-publish:
    <<: *default-pkg
    image: brsynth/twine
    build:
      context: ..
      args:
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: docker/twine.dockerfile
    command: sh -c "
                python3 setup.py sdist bdist_wheel
             && python3 -m twine upload --repository ${TEST}pypi dist/*"

  pkg-test:
    <<: *default-pkg
    build:
      context: ..
      args:
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: docker/tests.dockerfile
    command: pytest
