name: Update conda-forge feedstock recipe

on:
  push:
    branches:
      - stable

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout feedstock fork
        uses: actions/checkout@v2
        with:
          repository: brsynth/brs_utils-feedstock
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          token: ${{ secrets.GITHUB_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
          # path: my-tools
      - name: Update recipe
        run: |
          wget -O- https://github.com/brsynth/brs-utils/archive/refs/tags/$VERSION.tar.gz | shasum -a 256 > sha.txt
          sha=`python -c "f = open('sha.txt'); print(f.read().split()[0]); f.close()"`
          rm -f sha.txt
          sed -i -E "s/(\{% set version = \")[^>]+(\" %\})/\1somethin\2/" recipe/meta.yaml
          sed -i -E "s/(sha256: )[^>]+/\1$sha/" recipe/meta.yaml
          git config --local user.email "$GITHUB_EMAIL"
          git config --local user.name "$GITHUB_USERNAME"
          git commit -m "chore(meta.yml): update version" -a
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: brsynth
          GITHUB_EMAIL: joan.herisson@univ-evry.fr
          # DEPLOY_URL: github.com/conda-forge/brs_utils-feedstock
          VERSION: ${{ steps.tag_version.outputs.new_tag }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: brsynth/brs_utils-feedstock
          # branch: ${{ github.ref }}
