name: Create Tag

on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v5.6
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create tag
      uses: actions/github-script@v3
      env:
        VERSION: ${{ grep -Eo '[0-9](\.[0-9])+' */_version.py }}
      with:
        github-token: ${{ github.token }}
        script: |
          const VERSION = process.env
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${VERSION}",
            sha: context.sha
          })
