# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test on Windows

on:

  push:
    branches: [ win ]
    paths:
      - '**.yml'
  pull_request:
    branches: [ main, master ]

jobs:

  Test:

    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]

    steps:
    - name: Checkout package repository
      uses: actions/checkout@v2

    - name: Deploying miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-activate-base: true
        activate-environment: ""

    - name: Creating environment
      run: |
        conda env create --force -f environment.yaml -n test
        conda activate test

    - name: Adding testing tools
      run: conda install -y python pytest

    - name: Running tests
      run: python -m pytest
