# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:

  push:
    branches: [ main, master, dev ]
    paths-ignore:
      - '**/RELEASE*'
      - '**/README*'
      - '**/LICENSE*'
      - 'recipe'
      - 'docs'
      - '.gitignore'
      - '.github'
      - '!.github/workflows/test*'
      - '**/_version.py'
  pull_request:
    branches: [ master ]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
      # 1. Retrieving repository
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 2. Setting up conda env
      - name: "Set up conda environment"
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: false
          activate-environment: brs_utils-dev
          environment-file: environment.yaml

      # 3. Installing Python dependencies (test)
      - name: "Install Python dependencies"
        run: |
          conda install -c conda-forge pytest pytest-cov

      # 4. Running tests
      - name: "Running Tests"
        run: |
          cd tests
          pytest -v --cov --cov-report term-missing
