# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:

  push:
    branches: [ main, master, dev ]
    paths:
      - 'brs_utils/**'
      - 'tests/**'
  pull_request:
    branches: [ master ]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
      # 1. Retrieving repository
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 2. Setting up conda env
      - name: "Set up conda environment"
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: false
          activate-environment: brs_utils-dev
          environment-file: environment.yaml

      # 3. Installing Python dependencies (test)
      - name: "Install Python dependencies"
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pytest pytest-cov pytest-mock

      # 4. Running tests
      - name: "Running Tests"
        shell: bash -l {0}
        run: |
          python -m pytest -v --cov --cov-report term-missing

      # 5. Update feedstock
      - name: Checkout feedstock fork
        uses: actions/checkout@v2
        with:
          repository: brsynth/brs_utils-feedstock
          persist-credentials: false
          fetch-depth: 0
          path: feedstock
      - name: Update recipe
        run: |
          cd feedstock
          wget -O- https://github.com/brsynth/brs-utils/archive/refs/tags/$VERSION.tar.gz | shasum -a 256 > sha.txt
          sha=`python -c "f = open('sha.txt'); print(f.read().split()[0]); f.close()"`
          rm -f sha.txt
          sed -i -E "s/(\{% set version = \")[^>]+(\" %\})/\1$VERSION\2/" recipe/meta.yaml
          sed -i -E "s/(sha256: )[^>]+/\1$sha/" recipe/meta.yaml
          git config --local user.email "$GITHUB_EMAIL"
          git config --local user.name "$GITHUB_USERNAME"
          git commit -m "chore(meta.yml): update version" -a
        env:
          GITHUB_USERNAME: brsynth
          GITHUB_EMAIL: joan.herisson@univ-evry.fr
          VERSION: ${{ steps.tag_version.outputs.new_tag }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.FEEDSTOCK }}
          repository: brsynth/brs_utils-feedstock
          directory: feedstock
